name: Job Alert Scraper

on:
  schedule:
    - cron: '30 4 * * 1-5'    # 9:30 AM Pakistan (Mon–Fri)
    - cron: '0 9 * * 1-5'     # 2:00 PM
    - cron: '15 15 * * 1-5'   # 8:15 PM
    - cron: '0 18 * * 1-5'    # 11:00 PM
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job alert script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py
