name: Job Scraper and Emailer

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '30 4,9,15,18 * * 1,2,3,5'  # Runs at 9:30 AM, 2 PM, 8 PM, 11 PM (Pakistan time is UTC+5)

jobs:
  run-job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run job scraper script
        env:
          EMAIL_USER: ${{ secrets.EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py
